//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\joao\\Desktop\\MFES-RTFS\\Jogador.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.HashSet;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Jogador implements EvaluatePP {

// ***** VDMTOOLS START Name=totalPieces KEEP=NO
  private volatile Number totalPieces = null;
// ***** VDMTOOLS END Name=totalPieces

// ***** VDMTOOLS START Name=pecas KEEP=NO
  private volatile Set pecas = new HashSet();
// ***** VDMTOOLS END Name=pecas

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=JogadorSentinel KEEP=NO
  class JogadorSentinel extends Sentinel {

    public final int perdeu = 0;

    public final int Jogador = 1;

    public final int getPecas = 2;

    public final int resetPecas = 3;

    public final int decTotalPieces = 4;

    public final int VerificaSeTemPeca = 5;

    public final int nr_functions = 6;


    public JogadorSentinel () throws CGException {}


    public JogadorSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=JogadorSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new JogadorSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel

// ***** VDMTOOLS START Name=TOTAL_PIECES KEEP=NO
  public static final Number TOTAL_PIECES = new Integer(8);
// ***** VDMTOOLS END Name=TOTAL_PIECES


// ***** VDMTOOLS START Name=vdm_init_Jogador KEEP=NO
  private void vdm_init_Jogador () {
    try {
      setSentinel();
      totalPieces = TOTAL_PIECES;
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Jogador


// ***** VDMTOOLS START Name=inv_Jogador KEEP=NO
  public Boolean inv_Jogador () {
    return Boolean.valueOf(totalPieces.intValue() >= 0);
  }
// ***** VDMTOOLS END Name=inv_Jogador


// ***** VDMTOOLS START Name=Jogador KEEP=NO
  public Jogador () throws CGException {
    vdm_init_Jogador();
  }
// ***** VDMTOOLS END Name=Jogador


// ***** VDMTOOLS START Name=Jogador#1|Number KEEP=NO
  public Jogador (final Number tipo) throws CGException {
    vdm_init_Jogador();
    if (!this.pre_Jogador(tipo).booleanValue()) 
      UTIL.RunTime("Precondition failure in Jogador");
    if (tipo.intValue() == 1) {
      Set rhs_5 = new HashSet();
      rhs_5.add(new quotes.RATO1());
      rhs_5.add(new quotes.GATO1());
      rhs_5.add(new quotes.LOBO1());
      rhs_5.add(new quotes.CAO1());
      rhs_5.add(new quotes.LEOPARDO1());
      rhs_5.add(new quotes.TIGRE1());
      rhs_5.add(new quotes.LEAO1());
      rhs_5.add(new quotes.ELEFANTE1());
      pecas = (Set)UTIL.clone(rhs_5);
    }
    if (tipo.intValue() == 2) {
      Set rhs_17 = new HashSet();
      rhs_17.add(new quotes.RATO2());
      rhs_17.add(new quotes.GATO2());
      rhs_17.add(new quotes.LOBO2());
      rhs_17.add(new quotes.CAO2());
      rhs_17.add(new quotes.LEOPARDO2());
      rhs_17.add(new quotes.TIGRE2());
      rhs_17.add(new quotes.LEAO2());
      rhs_17.add(new quotes.ELEFANTE2());
      pecas = (Set)UTIL.clone(rhs_17);
    }
    else {
      UTIL.RunTime("The operation did not return a value");
      return new Jogador();
    }
  }
// ***** VDMTOOLS END Name=Jogador#1|Number


// ***** VDMTOOLS START Name=pre_Jogador#1|Number KEEP=NO
  public Boolean pre_Jogador (final Number tipo) throws CGException {
    Boolean varRes_2 = null;
    if (!(varRes_2 = Boolean.valueOf(tipo.intValue() == 1)).booleanValue()) 
      varRes_2 = Boolean.valueOf(tipo.intValue() == 2);
    return varRes_2;
  }
// ***** VDMTOOLS END Name=pre_Jogador#1|Number


// ***** VDMTOOLS START Name=getPecas KEEP=NO
  public Number getPecas () throws CGException {
    sentinel.entering(((JogadorSentinel)sentinel).getPecas);
    try {
      return totalPieces;
    }
    finally {
      sentinel.leaving(((JogadorSentinel)sentinel).getPecas);
    }
  }
// ***** VDMTOOLS END Name=getPecas


// ***** VDMTOOLS START Name=perdeu KEEP=NO
  public Boolean perdeu () throws CGException {
    sentinel.entering(((JogadorSentinel)sentinel).perdeu);
    try {
      return Boolean.valueOf(totalPieces.intValue() == 0);
    }
    finally {
      sentinel.leaving(((JogadorSentinel)sentinel).perdeu);
    }
  }
// ***** VDMTOOLS END Name=perdeu


// ***** VDMTOOLS START Name=resetPecas KEEP=NO
  public void resetPecas () throws CGException {
    sentinel.entering(((JogadorSentinel)sentinel).resetPecas);
    try {
      totalPieces = UTIL.NumberToInt(UTIL.clone(TOTAL_PIECES));
      if (!this.inv_Jogador().booleanValue()) 
        UTIL.RunTime("Instance invariant failure in Jogador");
    }
    finally {
      sentinel.leaving(((JogadorSentinel)sentinel).resetPecas);
    }
  }
// ***** VDMTOOLS END Name=resetPecas


// ***** VDMTOOLS START Name=decTotalPieces KEEP=NO
  public void decTotalPieces () throws CGException {
    sentinel.entering(((JogadorSentinel)sentinel).decTotalPieces);
    try {
      if (!this.pre_decTotalPieces().booleanValue()) 
        UTIL.RunTime("Precondition failure in decTotalPieces");
      Number rhs_4 = new Integer(totalPieces.intValue() - 1);
      if (!UTIL.IsNat(((Object)rhs_4))) 
        UTIL.RunTime("Incompatible type");
      totalPieces = UTIL.NumberToInt(UTIL.clone(rhs_4));
      if (!this.inv_Jogador().booleanValue()) 
        UTIL.RunTime("Instance invariant failure in Jogador");
    }
    finally {
      sentinel.leaving(((JogadorSentinel)sentinel).decTotalPieces);
    }
  }
// ***** VDMTOOLS END Name=decTotalPieces


// ***** VDMTOOLS START Name=pre_decTotalPieces KEEP=NO
  public Boolean pre_decTotalPieces () throws CGException {
    return Boolean.valueOf((totalPieces.intValue() - 1) >= 0);
  }
// ***** VDMTOOLS END Name=pre_decTotalPieces


// ***** VDMTOOLS START Name=VerificaSeTemPeca#1|Object KEEP=NO
  public Boolean VerificaSeTemPeca (final Object peca) throws CGException {
    sentinel.entering(((JogadorSentinel)sentinel).VerificaSeTemPeca);
    try {
      return Boolean.valueOf(UTIL.Contains(pecas, peca));
    }
    finally {
      sentinel.leaving(((JogadorSentinel)sentinel).VerificaSeTemPeca);
    }
  }
// ***** VDMTOOLS END Name=VerificaSeTemPeca#1|Object

}
;
