//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\joao\\Desktop\\MFES-RTFS\\Tabuleiro.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.ArrayList;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Tabuleiro implements EvaluatePP {

// ***** VDMTOOLS START Name=tab KEEP=NO
  private volatile Map tab = new HashMap();
// ***** VDMTOOLS END Name=tab

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=TabuleiroSentinel KEEP=NO
  class TabuleiroSentinel extends Sentinel {

    public final int reset = 0;

    public final int jogada = 1;

    public final int getBoard = 2;

    public final int getPiece = 3;

    public final int Tabuleiro = 4;

    public final int validCoords = 5;

    public final int validaDistancia = 6;

    public final int validaMaisForte = 7;

    public final int validaOrigemAnimal = 8;

    public final int nr_functions = 9;


    public TabuleiroSentinel () throws CGException {}


    public TabuleiroSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=TabuleiroSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new TabuleiroSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Tabuleiro KEEP=NO
  private void vdm_init_Tabuleiro () {
    try {
      setSentinel();
      tab = new HashMap();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Tabuleiro


// ***** VDMTOOLS START Name=Tabuleiro KEEP=NO
  public Tabuleiro () throws CGException {
    try {
      vdm_init_Tabuleiro();
      Map rhs_1 = new HashMap();
      List tmpSeq_3 = new ArrayList();
      tmpSeq_3.add(new Integer(1));
      tmpSeq_3.add(new Integer(1));
      rhs_1.put(tmpSeq_3, new quotes.LEAO1());
      List tmpSeq_8 = new ArrayList();
      tmpSeq_8.add(new Integer(1));
      tmpSeq_8.add(new Integer(2));
      rhs_1.put(tmpSeq_8, new quotes.VAZIO());
      List tmpSeq_13 = new ArrayList();
      tmpSeq_13.add(new Integer(1));
      tmpSeq_13.add(new Integer(3));
      rhs_1.put(tmpSeq_13, new quotes.TRAP());
      List tmpSeq_18 = new ArrayList();
      tmpSeq_18.add(new Integer(1));
      tmpSeq_18.add(new Integer(4));
      rhs_1.put(tmpSeq_18, new quotes.TOCA());
      List tmpSeq_23 = new ArrayList();
      tmpSeq_23.add(new Integer(1));
      tmpSeq_23.add(new Integer(5));
      rhs_1.put(tmpSeq_23, new quotes.TRAP());
      List tmpSeq_28 = new ArrayList();
      tmpSeq_28.add(new Integer(1));
      tmpSeq_28.add(new Integer(6));
      rhs_1.put(tmpSeq_28, new quotes.VAZIO());
      List tmpSeq_33 = new ArrayList();
      tmpSeq_33.add(new Integer(1));
      tmpSeq_33.add(new Integer(7));
      rhs_1.put(tmpSeq_33, new quotes.TIGRE1());
      List tmpSeq_38 = new ArrayList();
      tmpSeq_38.add(new Integer(2));
      tmpSeq_38.add(new Integer(1));
      rhs_1.put(tmpSeq_38, new quotes.VAZIO());
      List tmpSeq_43 = new ArrayList();
      tmpSeq_43.add(new Integer(2));
      tmpSeq_43.add(new Integer(2));
      rhs_1.put(tmpSeq_43, new quotes.CAO1());
      List tmpSeq_48 = new ArrayList();
      tmpSeq_48.add(new Integer(2));
      tmpSeq_48.add(new Integer(3));
      rhs_1.put(tmpSeq_48, new quotes.VAZIO());
      List tmpSeq_53 = new ArrayList();
      tmpSeq_53.add(new Integer(2));
      tmpSeq_53.add(new Integer(4));
      rhs_1.put(tmpSeq_53, new quotes.TRAP());
      List tmpSeq_58 = new ArrayList();
      tmpSeq_58.add(new Integer(2));
      tmpSeq_58.add(new Integer(5));
      rhs_1.put(tmpSeq_58, new quotes.VAZIO());
      List tmpSeq_63 = new ArrayList();
      tmpSeq_63.add(new Integer(2));
      tmpSeq_63.add(new Integer(6));
      rhs_1.put(tmpSeq_63, new quotes.GATO1());
      List tmpSeq_68 = new ArrayList();
      tmpSeq_68.add(new Integer(2));
      tmpSeq_68.add(new Integer(7));
      rhs_1.put(tmpSeq_68, new quotes.VAZIO());
      List tmpSeq_73 = new ArrayList();
      tmpSeq_73.add(new Integer(3));
      tmpSeq_73.add(new Integer(1));
      rhs_1.put(tmpSeq_73, new quotes.RATO1());
      List tmpSeq_78 = new ArrayList();
      tmpSeq_78.add(new Integer(3));
      tmpSeq_78.add(new Integer(2));
      rhs_1.put(tmpSeq_78, new quotes.VAZIO());
      List tmpSeq_83 = new ArrayList();
      tmpSeq_83.add(new Integer(3));
      tmpSeq_83.add(new Integer(3));
      rhs_1.put(tmpSeq_83, new quotes.LEOPARDO1());
      List tmpSeq_88 = new ArrayList();
      tmpSeq_88.add(new Integer(3));
      tmpSeq_88.add(new Integer(4));
      rhs_1.put(tmpSeq_88, new quotes.VAZIO());
      List tmpSeq_93 = new ArrayList();
      tmpSeq_93.add(new Integer(3));
      tmpSeq_93.add(new Integer(5));
      rhs_1.put(tmpSeq_93, new quotes.LOBO1());
      List tmpSeq_98 = new ArrayList();
      tmpSeq_98.add(new Integer(3));
      tmpSeq_98.add(new Integer(6));
      rhs_1.put(tmpSeq_98, new quotes.VAZIO());
      List tmpSeq_103 = new ArrayList();
      tmpSeq_103.add(new Integer(3));
      tmpSeq_103.add(new Integer(7));
      rhs_1.put(tmpSeq_103, new quotes.ELEFANTE1());
      List tmpSeq_108 = new ArrayList();
      tmpSeq_108.add(new Integer(4));
      tmpSeq_108.add(new Integer(1));
      rhs_1.put(tmpSeq_108, new quotes.VAZIO());
      List tmpSeq_113 = new ArrayList();
      tmpSeq_113.add(new Integer(4));
      tmpSeq_113.add(new Integer(2));
      rhs_1.put(tmpSeq_113, new quotes.AGUA());
      List tmpSeq_118 = new ArrayList();
      tmpSeq_118.add(new Integer(4));
      tmpSeq_118.add(new Integer(3));
      rhs_1.put(tmpSeq_118, new quotes.AGUA());
      List tmpSeq_123 = new ArrayList();
      tmpSeq_123.add(new Integer(4));
      tmpSeq_123.add(new Integer(4));
      rhs_1.put(tmpSeq_123, new quotes.VAZIO());
      List tmpSeq_128 = new ArrayList();
      tmpSeq_128.add(new Integer(4));
      tmpSeq_128.add(new Integer(5));
      rhs_1.put(tmpSeq_128, new quotes.AGUA());
      List tmpSeq_133 = new ArrayList();
      tmpSeq_133.add(new Integer(4));
      tmpSeq_133.add(new Integer(6));
      rhs_1.put(tmpSeq_133, new quotes.AGUA());
      List tmpSeq_138 = new ArrayList();
      tmpSeq_138.add(new Integer(4));
      tmpSeq_138.add(new Integer(7));
      rhs_1.put(tmpSeq_138, new quotes.VAZIO());
      List tmpSeq_143 = new ArrayList();
      tmpSeq_143.add(new Integer(5));
      tmpSeq_143.add(new Integer(1));
      rhs_1.put(tmpSeq_143, new quotes.VAZIO());
      List tmpSeq_148 = new ArrayList();
      tmpSeq_148.add(new Integer(5));
      tmpSeq_148.add(new Integer(2));
      rhs_1.put(tmpSeq_148, new quotes.AGUA());
      List tmpSeq_153 = new ArrayList();
      tmpSeq_153.add(new Integer(5));
      tmpSeq_153.add(new Integer(3));
      rhs_1.put(tmpSeq_153, new quotes.AGUA());
      List tmpSeq_158 = new ArrayList();
      tmpSeq_158.add(new Integer(5));
      tmpSeq_158.add(new Integer(4));
      rhs_1.put(tmpSeq_158, new quotes.VAZIO());
      List tmpSeq_163 = new ArrayList();
      tmpSeq_163.add(new Integer(5));
      tmpSeq_163.add(new Integer(5));
      rhs_1.put(tmpSeq_163, new quotes.AGUA());
      List tmpSeq_168 = new ArrayList();
      tmpSeq_168.add(new Integer(5));
      tmpSeq_168.add(new Integer(6));
      rhs_1.put(tmpSeq_168, new quotes.AGUA());
      List tmpSeq_173 = new ArrayList();
      tmpSeq_173.add(new Integer(5));
      tmpSeq_173.add(new Integer(7));
      rhs_1.put(tmpSeq_173, new quotes.VAZIO());
      List tmpSeq_178 = new ArrayList();
      tmpSeq_178.add(new Integer(6));
      tmpSeq_178.add(new Integer(1));
      rhs_1.put(tmpSeq_178, new quotes.VAZIO());
      List tmpSeq_183 = new ArrayList();
      tmpSeq_183.add(new Integer(6));
      tmpSeq_183.add(new Integer(2));
      rhs_1.put(tmpSeq_183, new quotes.AGUA());
      List tmpSeq_188 = new ArrayList();
      tmpSeq_188.add(new Integer(6));
      tmpSeq_188.add(new Integer(3));
      rhs_1.put(tmpSeq_188, new quotes.AGUA());
      List tmpSeq_193 = new ArrayList();
      tmpSeq_193.add(new Integer(6));
      tmpSeq_193.add(new Integer(4));
      rhs_1.put(tmpSeq_193, new quotes.VAZIO());
      List tmpSeq_198 = new ArrayList();
      tmpSeq_198.add(new Integer(6));
      tmpSeq_198.add(new Integer(5));
      rhs_1.put(tmpSeq_198, new quotes.AGUA());
      List tmpSeq_203 = new ArrayList();
      tmpSeq_203.add(new Integer(6));
      tmpSeq_203.add(new Integer(6));
      rhs_1.put(tmpSeq_203, new quotes.AGUA());
      List tmpSeq_208 = new ArrayList();
      tmpSeq_208.add(new Integer(6));
      tmpSeq_208.add(new Integer(7));
      rhs_1.put(tmpSeq_208, new quotes.VAZIO());
      List tmpSeq_213 = new ArrayList();
      tmpSeq_213.add(new Integer(7));
      tmpSeq_213.add(new Integer(1));
      rhs_1.put(tmpSeq_213, new quotes.ELEFANTE2());
      List tmpSeq_218 = new ArrayList();
      tmpSeq_218.add(new Integer(7));
      tmpSeq_218.add(new Integer(2));
      rhs_1.put(tmpSeq_218, new quotes.VAZIO());
      List tmpSeq_223 = new ArrayList();
      tmpSeq_223.add(new Integer(7));
      tmpSeq_223.add(new Integer(3));
      rhs_1.put(tmpSeq_223, new quotes.LOBO2());
      List tmpSeq_228 = new ArrayList();
      tmpSeq_228.add(new Integer(7));
      tmpSeq_228.add(new Integer(4));
      rhs_1.put(tmpSeq_228, new quotes.VAZIO());
      List tmpSeq_233 = new ArrayList();
      tmpSeq_233.add(new Integer(7));
      tmpSeq_233.add(new Integer(5));
      rhs_1.put(tmpSeq_233, new quotes.LEOPARDO2());
      List tmpSeq_238 = new ArrayList();
      tmpSeq_238.add(new Integer(7));
      tmpSeq_238.add(new Integer(6));
      rhs_1.put(tmpSeq_238, new quotes.VAZIO());
      List tmpSeq_243 = new ArrayList();
      tmpSeq_243.add(new Integer(7));
      tmpSeq_243.add(new Integer(7));
      rhs_1.put(tmpSeq_243, new quotes.RATO2());
      List tmpSeq_248 = new ArrayList();
      tmpSeq_248.add(new Integer(8));
      tmpSeq_248.add(new Integer(1));
      rhs_1.put(tmpSeq_248, new quotes.VAZIO());
      List tmpSeq_253 = new ArrayList();
      tmpSeq_253.add(new Integer(8));
      tmpSeq_253.add(new Integer(2));
      rhs_1.put(tmpSeq_253, new quotes.GATO2());
      List tmpSeq_258 = new ArrayList();
      tmpSeq_258.add(new Integer(8));
      tmpSeq_258.add(new Integer(3));
      rhs_1.put(tmpSeq_258, new quotes.VAZIO());
      List tmpSeq_263 = new ArrayList();
      tmpSeq_263.add(new Integer(8));
      tmpSeq_263.add(new Integer(4));
      rhs_1.put(tmpSeq_263, new quotes.TRAP());
      List tmpSeq_268 = new ArrayList();
      tmpSeq_268.add(new Integer(8));
      tmpSeq_268.add(new Integer(5));
      rhs_1.put(tmpSeq_268, new quotes.VAZIO());
      List tmpSeq_273 = new ArrayList();
      tmpSeq_273.add(new Integer(8));
      tmpSeq_273.add(new Integer(6));
      rhs_1.put(tmpSeq_273, new quotes.CAO2());
      List tmpSeq_278 = new ArrayList();
      tmpSeq_278.add(new Integer(8));
      tmpSeq_278.add(new Integer(7));
      rhs_1.put(tmpSeq_278, new quotes.VAZIO());
      List tmpSeq_283 = new ArrayList();
      tmpSeq_283.add(new Integer(9));
      tmpSeq_283.add(new Integer(1));
      rhs_1.put(tmpSeq_283, new quotes.TIGRE2());
      List tmpSeq_288 = new ArrayList();
      tmpSeq_288.add(new Integer(9));
      tmpSeq_288.add(new Integer(2));
      rhs_1.put(tmpSeq_288, new quotes.VAZIO());
      List tmpSeq_293 = new ArrayList();
      tmpSeq_293.add(new Integer(9));
      tmpSeq_293.add(new Integer(3));
      rhs_1.put(tmpSeq_293, new quotes.TRAP());
      List tmpSeq_298 = new ArrayList();
      tmpSeq_298.add(new Integer(9));
      tmpSeq_298.add(new Integer(4));
      rhs_1.put(tmpSeq_298, new quotes.TOCA());
      List tmpSeq_303 = new ArrayList();
      tmpSeq_303.add(new Integer(9));
      tmpSeq_303.add(new Integer(5));
      rhs_1.put(tmpSeq_303, new quotes.TRAP());
      List tmpSeq_308 = new ArrayList();
      tmpSeq_308.add(new Integer(9));
      tmpSeq_308.add(new Integer(6));
      rhs_1.put(tmpSeq_308, new quotes.VAZIO());
      List tmpSeq_313 = new ArrayList();
      tmpSeq_313.add(new Integer(9));
      tmpSeq_313.add(new Integer(7));
      rhs_1.put(tmpSeq_313, new quotes.LEAO2());
      tab = (Map)UTIL.clone(rhs_1);
      setSentinel();
    }
    catch (Throwable e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Tabuleiro


// ***** VDMTOOLS START Name=reset KEEP=NO
  public void reset () throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).reset);
    try {
      Map rhs_1 = new HashMap();
      List tmpSeq_3 = new ArrayList();
      tmpSeq_3.add(new Integer(1));
      tmpSeq_3.add(new Integer(1));
      rhs_1.put(tmpSeq_3, new quotes.LEAO1());
      List tmpSeq_8 = new ArrayList();
      tmpSeq_8.add(new Integer(1));
      tmpSeq_8.add(new Integer(2));
      rhs_1.put(tmpSeq_8, new quotes.VAZIO());
      List tmpSeq_13 = new ArrayList();
      tmpSeq_13.add(new Integer(1));
      tmpSeq_13.add(new Integer(3));
      rhs_1.put(tmpSeq_13, new quotes.TRAP());
      List tmpSeq_18 = new ArrayList();
      tmpSeq_18.add(new Integer(1));
      tmpSeq_18.add(new Integer(4));
      rhs_1.put(tmpSeq_18, new quotes.TOCA());
      List tmpSeq_23 = new ArrayList();
      tmpSeq_23.add(new Integer(1));
      tmpSeq_23.add(new Integer(5));
      rhs_1.put(tmpSeq_23, new quotes.TRAP());
      List tmpSeq_28 = new ArrayList();
      tmpSeq_28.add(new Integer(1));
      tmpSeq_28.add(new Integer(6));
      rhs_1.put(tmpSeq_28, new quotes.VAZIO());
      List tmpSeq_33 = new ArrayList();
      tmpSeq_33.add(new Integer(1));
      tmpSeq_33.add(new Integer(7));
      rhs_1.put(tmpSeq_33, new quotes.TIGRE1());
      List tmpSeq_38 = new ArrayList();
      tmpSeq_38.add(new Integer(2));
      tmpSeq_38.add(new Integer(1));
      rhs_1.put(tmpSeq_38, new quotes.VAZIO());
      List tmpSeq_43 = new ArrayList();
      tmpSeq_43.add(new Integer(2));
      tmpSeq_43.add(new Integer(2));
      rhs_1.put(tmpSeq_43, new quotes.CAO1());
      List tmpSeq_48 = new ArrayList();
      tmpSeq_48.add(new Integer(2));
      tmpSeq_48.add(new Integer(3));
      rhs_1.put(tmpSeq_48, new quotes.VAZIO());
      List tmpSeq_53 = new ArrayList();
      tmpSeq_53.add(new Integer(2));
      tmpSeq_53.add(new Integer(4));
      rhs_1.put(tmpSeq_53, new quotes.TRAP());
      List tmpSeq_58 = new ArrayList();
      tmpSeq_58.add(new Integer(2));
      tmpSeq_58.add(new Integer(5));
      rhs_1.put(tmpSeq_58, new quotes.VAZIO());
      List tmpSeq_63 = new ArrayList();
      tmpSeq_63.add(new Integer(2));
      tmpSeq_63.add(new Integer(6));
      rhs_1.put(tmpSeq_63, new quotes.GATO1());
      List tmpSeq_68 = new ArrayList();
      tmpSeq_68.add(new Integer(2));
      tmpSeq_68.add(new Integer(7));
      rhs_1.put(tmpSeq_68, new quotes.VAZIO());
      List tmpSeq_73 = new ArrayList();
      tmpSeq_73.add(new Integer(3));
      tmpSeq_73.add(new Integer(1));
      rhs_1.put(tmpSeq_73, new quotes.RATO1());
      List tmpSeq_78 = new ArrayList();
      tmpSeq_78.add(new Integer(3));
      tmpSeq_78.add(new Integer(2));
      rhs_1.put(tmpSeq_78, new quotes.VAZIO());
      List tmpSeq_83 = new ArrayList();
      tmpSeq_83.add(new Integer(3));
      tmpSeq_83.add(new Integer(3));
      rhs_1.put(tmpSeq_83, new quotes.LEOPARDO1());
      List tmpSeq_88 = new ArrayList();
      tmpSeq_88.add(new Integer(3));
      tmpSeq_88.add(new Integer(4));
      rhs_1.put(tmpSeq_88, new quotes.VAZIO());
      List tmpSeq_93 = new ArrayList();
      tmpSeq_93.add(new Integer(3));
      tmpSeq_93.add(new Integer(5));
      rhs_1.put(tmpSeq_93, new quotes.LOBO1());
      List tmpSeq_98 = new ArrayList();
      tmpSeq_98.add(new Integer(3));
      tmpSeq_98.add(new Integer(6));
      rhs_1.put(tmpSeq_98, new quotes.VAZIO());
      List tmpSeq_103 = new ArrayList();
      tmpSeq_103.add(new Integer(3));
      tmpSeq_103.add(new Integer(7));
      rhs_1.put(tmpSeq_103, new quotes.ELEFANTE1());
      List tmpSeq_108 = new ArrayList();
      tmpSeq_108.add(new Integer(4));
      tmpSeq_108.add(new Integer(1));
      rhs_1.put(tmpSeq_108, new quotes.VAZIO());
      List tmpSeq_113 = new ArrayList();
      tmpSeq_113.add(new Integer(4));
      tmpSeq_113.add(new Integer(2));
      rhs_1.put(tmpSeq_113, new quotes.AGUA());
      List tmpSeq_118 = new ArrayList();
      tmpSeq_118.add(new Integer(4));
      tmpSeq_118.add(new Integer(3));
      rhs_1.put(tmpSeq_118, new quotes.AGUA());
      List tmpSeq_123 = new ArrayList();
      tmpSeq_123.add(new Integer(4));
      tmpSeq_123.add(new Integer(4));
      rhs_1.put(tmpSeq_123, new quotes.VAZIO());
      List tmpSeq_128 = new ArrayList();
      tmpSeq_128.add(new Integer(4));
      tmpSeq_128.add(new Integer(5));
      rhs_1.put(tmpSeq_128, new quotes.AGUA());
      List tmpSeq_133 = new ArrayList();
      tmpSeq_133.add(new Integer(4));
      tmpSeq_133.add(new Integer(6));
      rhs_1.put(tmpSeq_133, new quotes.AGUA());
      List tmpSeq_138 = new ArrayList();
      tmpSeq_138.add(new Integer(4));
      tmpSeq_138.add(new Integer(7));
      rhs_1.put(tmpSeq_138, new quotes.VAZIO());
      List tmpSeq_143 = new ArrayList();
      tmpSeq_143.add(new Integer(5));
      tmpSeq_143.add(new Integer(1));
      rhs_1.put(tmpSeq_143, new quotes.VAZIO());
      List tmpSeq_148 = new ArrayList();
      tmpSeq_148.add(new Integer(5));
      tmpSeq_148.add(new Integer(2));
      rhs_1.put(tmpSeq_148, new quotes.AGUA());
      List tmpSeq_153 = new ArrayList();
      tmpSeq_153.add(new Integer(5));
      tmpSeq_153.add(new Integer(3));
      rhs_1.put(tmpSeq_153, new quotes.AGUA());
      List tmpSeq_158 = new ArrayList();
      tmpSeq_158.add(new Integer(5));
      tmpSeq_158.add(new Integer(4));
      rhs_1.put(tmpSeq_158, new quotes.VAZIO());
      List tmpSeq_163 = new ArrayList();
      tmpSeq_163.add(new Integer(5));
      tmpSeq_163.add(new Integer(5));
      rhs_1.put(tmpSeq_163, new quotes.AGUA());
      List tmpSeq_168 = new ArrayList();
      tmpSeq_168.add(new Integer(5));
      tmpSeq_168.add(new Integer(6));
      rhs_1.put(tmpSeq_168, new quotes.AGUA());
      List tmpSeq_173 = new ArrayList();
      tmpSeq_173.add(new Integer(5));
      tmpSeq_173.add(new Integer(7));
      rhs_1.put(tmpSeq_173, new quotes.VAZIO());
      List tmpSeq_178 = new ArrayList();
      tmpSeq_178.add(new Integer(6));
      tmpSeq_178.add(new Integer(1));
      rhs_1.put(tmpSeq_178, new quotes.VAZIO());
      List tmpSeq_183 = new ArrayList();
      tmpSeq_183.add(new Integer(6));
      tmpSeq_183.add(new Integer(2));
      rhs_1.put(tmpSeq_183, new quotes.AGUA());
      List tmpSeq_188 = new ArrayList();
      tmpSeq_188.add(new Integer(6));
      tmpSeq_188.add(new Integer(3));
      rhs_1.put(tmpSeq_188, new quotes.AGUA());
      List tmpSeq_193 = new ArrayList();
      tmpSeq_193.add(new Integer(6));
      tmpSeq_193.add(new Integer(4));
      rhs_1.put(tmpSeq_193, new quotes.VAZIO());
      List tmpSeq_198 = new ArrayList();
      tmpSeq_198.add(new Integer(6));
      tmpSeq_198.add(new Integer(5));
      rhs_1.put(tmpSeq_198, new quotes.AGUA());
      List tmpSeq_203 = new ArrayList();
      tmpSeq_203.add(new Integer(6));
      tmpSeq_203.add(new Integer(6));
      rhs_1.put(tmpSeq_203, new quotes.AGUA());
      List tmpSeq_208 = new ArrayList();
      tmpSeq_208.add(new Integer(6));
      tmpSeq_208.add(new Integer(7));
      rhs_1.put(tmpSeq_208, new quotes.VAZIO());
      List tmpSeq_213 = new ArrayList();
      tmpSeq_213.add(new Integer(7));
      tmpSeq_213.add(new Integer(1));
      rhs_1.put(tmpSeq_213, new quotes.ELEFANTE2());
      List tmpSeq_218 = new ArrayList();
      tmpSeq_218.add(new Integer(7));
      tmpSeq_218.add(new Integer(2));
      rhs_1.put(tmpSeq_218, new quotes.VAZIO());
      List tmpSeq_223 = new ArrayList();
      tmpSeq_223.add(new Integer(7));
      tmpSeq_223.add(new Integer(3));
      rhs_1.put(tmpSeq_223, new quotes.LOBO2());
      List tmpSeq_228 = new ArrayList();
      tmpSeq_228.add(new Integer(7));
      tmpSeq_228.add(new Integer(4));
      rhs_1.put(tmpSeq_228, new quotes.VAZIO());
      List tmpSeq_233 = new ArrayList();
      tmpSeq_233.add(new Integer(7));
      tmpSeq_233.add(new Integer(5));
      rhs_1.put(tmpSeq_233, new quotes.LEOPARDO2());
      List tmpSeq_238 = new ArrayList();
      tmpSeq_238.add(new Integer(7));
      tmpSeq_238.add(new Integer(6));
      rhs_1.put(tmpSeq_238, new quotes.VAZIO());
      List tmpSeq_243 = new ArrayList();
      tmpSeq_243.add(new Integer(7));
      tmpSeq_243.add(new Integer(7));
      rhs_1.put(tmpSeq_243, new quotes.RATO2());
      List tmpSeq_248 = new ArrayList();
      tmpSeq_248.add(new Integer(8));
      tmpSeq_248.add(new Integer(1));
      rhs_1.put(tmpSeq_248, new quotes.VAZIO());
      List tmpSeq_253 = new ArrayList();
      tmpSeq_253.add(new Integer(8));
      tmpSeq_253.add(new Integer(2));
      rhs_1.put(tmpSeq_253, new quotes.GATO2());
      List tmpSeq_258 = new ArrayList();
      tmpSeq_258.add(new Integer(8));
      tmpSeq_258.add(new Integer(3));
      rhs_1.put(tmpSeq_258, new quotes.VAZIO());
      List tmpSeq_263 = new ArrayList();
      tmpSeq_263.add(new Integer(8));
      tmpSeq_263.add(new Integer(4));
      rhs_1.put(tmpSeq_263, new quotes.TRAP());
      List tmpSeq_268 = new ArrayList();
      tmpSeq_268.add(new Integer(8));
      tmpSeq_268.add(new Integer(5));
      rhs_1.put(tmpSeq_268, new quotes.VAZIO());
      List tmpSeq_273 = new ArrayList();
      tmpSeq_273.add(new Integer(8));
      tmpSeq_273.add(new Integer(6));
      rhs_1.put(tmpSeq_273, new quotes.CAO2());
      List tmpSeq_278 = new ArrayList();
      tmpSeq_278.add(new Integer(8));
      tmpSeq_278.add(new Integer(7));
      rhs_1.put(tmpSeq_278, new quotes.VAZIO());
      List tmpSeq_283 = new ArrayList();
      tmpSeq_283.add(new Integer(9));
      tmpSeq_283.add(new Integer(1));
      rhs_1.put(tmpSeq_283, new quotes.TIGRE2());
      List tmpSeq_288 = new ArrayList();
      tmpSeq_288.add(new Integer(9));
      tmpSeq_288.add(new Integer(2));
      rhs_1.put(tmpSeq_288, new quotes.VAZIO());
      List tmpSeq_293 = new ArrayList();
      tmpSeq_293.add(new Integer(9));
      tmpSeq_293.add(new Integer(3));
      rhs_1.put(tmpSeq_293, new quotes.TRAP());
      List tmpSeq_298 = new ArrayList();
      tmpSeq_298.add(new Integer(9));
      tmpSeq_298.add(new Integer(4));
      rhs_1.put(tmpSeq_298, new quotes.TOCA());
      List tmpSeq_303 = new ArrayList();
      tmpSeq_303.add(new Integer(9));
      tmpSeq_303.add(new Integer(5));
      rhs_1.put(tmpSeq_303, new quotes.TRAP());
      List tmpSeq_308 = new ArrayList();
      tmpSeq_308.add(new Integer(9));
      tmpSeq_308.add(new Integer(6));
      rhs_1.put(tmpSeq_308, new quotes.VAZIO());
      List tmpSeq_313 = new ArrayList();
      tmpSeq_313.add(new Integer(9));
      tmpSeq_313.add(new Integer(7));
      rhs_1.put(tmpSeq_313, new quotes.LEAO2());
      tab = (Map)UTIL.clone(rhs_1);
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).reset);
    }
  }
// ***** VDMTOOLS END Name=reset


// ***** VDMTOOLS START Name=getPiece#1|List KEEP=NO
  public Object getPiece (final List coords) throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).getPiece);
    try {
      if (!this.pre_getPiece(coords).booleanValue()) 
        UTIL.RunTime("Precondition failure in getPiece");
      return tab.get(coords);
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).getPiece);
    }
  }
// ***** VDMTOOLS END Name=getPiece#1|List


// ***** VDMTOOLS START Name=pre_getPiece#1|List KEEP=NO
  public Boolean pre_getPiece (final List coords) throws CGException {
    Boolean varRes_2 = null;
    if ((varRes_2 = validCoords(coords)).booleanValue()) 
      varRes_2 = Boolean.valueOf(!UTIL.equals(tab, new HashMap()));
    return varRes_2;
  }
// ***** VDMTOOLS END Name=pre_getPiece#1|List


// ***** VDMTOOLS START Name=getBoard KEEP=NO
  public Map getBoard () throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).getBoard);
    try {
      return tab;
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).getBoard);
    }
  }
// ***** VDMTOOLS END Name=getBoard


// ***** VDMTOOLS START Name=validCoords#1|List KEEP=NO
  public Boolean validCoords (final List coord) throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).validCoords);
    try {
      if (!this.pre_validCoords(coord).booleanValue()) 
        UTIL.RunTime("Precondition failure in validCoords");
      return Boolean.valueOf(tab.containsKey(coord));
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).validCoords);
    }
  }
// ***** VDMTOOLS END Name=validCoords#1|List


// ***** VDMTOOLS START Name=pre_validCoords#1|List KEEP=NO
  public Boolean pre_validCoords (final List coord) throws CGException {
    return Boolean.valueOf(coord.size() == 2);
  }
// ***** VDMTOOLS END Name=pre_validCoords#1|List


// ***** VDMTOOLS START Name=jogada#2|List|List KEEP=NO
  public void jogada (final List origem, final List destino) throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).jogada);
    try {
      if (!this.pre_jogada(origem, destino).booleanValue()) 
        UTIL.RunTime("Precondition failure in jogada");
      tab.put(destino, tab.get(origem));
      tab.put(origem, new quotes.VAZIO());
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).jogada);
    }
  }
// ***** VDMTOOLS END Name=jogada#2|List|List


// ***** VDMTOOLS START Name=pre_jogada#2|List|List KEEP=NO
  public Boolean pre_jogada (final List origem, final List destino) throws CGException {
    Boolean varRes_3 = null;
    Boolean var1_4 = null;
    Boolean var1_5 = null;
    Boolean var1_6 = null;
    if ((var1_6 = validCoords(origem)).booleanValue()) 
      var1_6 = validCoords(destino);
    if ((var1_5 = var1_6).booleanValue()) 
      var1_5 = validaOrigemAnimal(origem);
    if ((var1_4 = var1_5).booleanValue()) 
      var1_4 = validaDistancia(origem, destino);
    if ((varRes_3 = var1_4).booleanValue()) 
      varRes_3 = validaMaisForte(origem, destino);
    return varRes_3;
  }
// ***** VDMTOOLS END Name=pre_jogada#2|List|List


// ***** VDMTOOLS START Name=validaOrigemAnimal#1|List KEEP=NO
  public Boolean validaOrigemAnimal (final List origem) throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).validaOrigemAnimal);
    try {
      if (!this.pre_validaOrigemAnimal(origem).booleanValue()) 
        UTIL.RunTime("Precondition failure in validaOrigemAnimal");
      Boolean cond_2 = null;
      Boolean var1_3 = null;
      if ((var1_3 = Boolean.valueOf(!UTIL.equals(tab.get(origem), new quotes.VAZIO()))).booleanValue()) 
        var1_3 = Boolean.valueOf(!UTIL.equals(tab.get(origem), new quotes.AGUA()));
      if ((cond_2 = var1_3).booleanValue()) 
        cond_2 = Boolean.valueOf(!UTIL.equals(tab.get(origem), new quotes.TRAP()));
      if (cond_2.booleanValue()) 
        return Boolean.TRUE;
      else 
        return Boolean.FALSE;
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).validaOrigemAnimal);
    }
  }
// ***** VDMTOOLS END Name=validaOrigemAnimal#1|List


// ***** VDMTOOLS START Name=pre_validaOrigemAnimal#1|List KEEP=NO
  public Boolean pre_validaOrigemAnimal (final List origem) throws CGException {
    return validCoords(origem);
  }
// ***** VDMTOOLS END Name=pre_validaOrigemAnimal#1|List


// ***** VDMTOOLS START Name=validaDistancia#2|List|List KEEP=NO
  public Boolean validaDistancia (final List origem, final List destino) throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).validaDistancia);
    try {
      if (!this.pre_validaDistancia(origem, destino).booleanValue()) 
        UTIL.RunTime("Precondition failure in validaDistancia");
      {
        Number distx = null;
        if ((1 > 1) || (1 > origem.size())) 
          UTIL.RunTime("Illegal index");
        if ((1 > 1) || (1 > destino.size())) 
          UTIL.RunTime("Illegal index");
        distx = new Integer(UTIL.NumberToInt(origem.get(0)).intValue() - UTIL.NumberToInt(destino.get(0)).intValue());
        Number disty = null;
        if ((1 > 2) || (2 > origem.size())) 
          UTIL.RunTime("Illegal index");
        if ((1 > 2) || (2 > destino.size())) 
          UTIL.RunTime("Illegal index");
        disty = new Integer(UTIL.NumberToInt(origem.get(1)).intValue() - UTIL.NumberToInt(destino.get(1)).intValue());
        Number distf = null;
        if (distx.intValue() < 0) 
          distx = new Integer(distx.intValue() * -1);
        if (disty.intValue() < 0) 
          disty = new Integer(disty.intValue() * -1);
        distf = new Integer(distx.intValue() + disty.intValue());
        if (distf.intValue() > 1) 
          return Boolean.FALSE;
        return Boolean.TRUE;
      }
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).validaDistancia);
    }
  }
// ***** VDMTOOLS END Name=validaDistancia#2|List|List


// ***** VDMTOOLS START Name=pre_validaDistancia#2|List|List KEEP=NO
  public Boolean pre_validaDistancia (final List origem, final List destino) throws CGException {
    Boolean varRes_3 = null;
    if ((varRes_3 = validCoords(origem)).booleanValue()) 
      varRes_3 = validCoords(destino);
    return varRes_3;
  }
// ***** VDMTOOLS END Name=pre_validaDistancia#2|List|List


// ***** VDMTOOLS START Name=validaMaisForte#2|List|List KEEP=NO
  public Boolean validaMaisForte (final List origem, final List destino) throws CGException {
    sentinel.entering(((TabuleiroSentinel)sentinel).validaMaisForte);
    try {
      if (!this.pre_validaMaisForte(origem, destino).booleanValue()) 
        UTIL.RunTime("Precondition failure in validaMaisForte");
      {
        List forca1 = null;
        List tmpSeq_3 = new ArrayList();
        tmpSeq_3.add(new quotes.VAZIO());
        tmpSeq_3.add(new quotes.TOCA());
        tmpSeq_3.add(new quotes.TRAP());
        tmpSeq_3.add(new quotes.RATO1());
        tmpSeq_3.add(new quotes.GATO1());
        tmpSeq_3.add(new quotes.LOBO1());
        tmpSeq_3.add(new quotes.CAO1());
        tmpSeq_3.add(new quotes.LEOPARDO1());
        tmpSeq_3.add(new quotes.TIGRE1());
        tmpSeq_3.add(new quotes.LEAO1());
        tmpSeq_3.add(new quotes.ELEFANTE1());
        tmpSeq_3.add(new quotes.AGUA());
        forca1 = tmpSeq_3;
        List forca2 = null;
        List tmpSeq_16 = new ArrayList();
        tmpSeq_16.add(new quotes.VAZIO());
        tmpSeq_16.add(new quotes.TOCA());
        tmpSeq_16.add(new quotes.TRAP());
        tmpSeq_16.add(new quotes.RATO2());
        tmpSeq_16.add(new quotes.GATO2());
        tmpSeq_16.add(new quotes.LOBO2());
        tmpSeq_16.add(new quotes.CAO2());
        tmpSeq_16.add(new quotes.LEOPARDO2());
        tmpSeq_16.add(new quotes.TIGRE2());
        tmpSeq_16.add(new quotes.LEAO2());
        tmpSeq_16.add(new quotes.ELEFANTE2());
        tmpSeq_16.add(new quotes.AGUA());
        forca2 = tmpSeq_16;
        Number indice_origem = null;
        Number indice_destino = null;
        for (int ilb_32 = 1; ilb_32 <= forca1.size(); ilb_32++) {
          Number i = new Integer(ilb_32);
          if ((1 > i.intValue()) || (i.intValue() > forca1.size())) 
            UTIL.RunTime("Illegal index");
          if (UTIL.equals(forca1.get(i.intValue() - 1), tab.get(origem))) 
            indice_origem = UTIL.NumberToInt(UTIL.clone(i));
        }
        for (int ilb_44 = 1; ilb_44 <= forca1.size(); ilb_44++) {
          Number i = new Integer(ilb_44);
          if ((1 > i.intValue()) || (i.intValue() > forca1.size())) 
            UTIL.RunTime("Illegal index");
          if (UTIL.equals(forca1.get(i.intValue() - 1), tab.get(destino))) 
            indice_destino = UTIL.NumberToInt(UTIL.clone(i));
        }
        for (int ilb_56 = 1; ilb_56 <= forca2.size(); ilb_56++) {
          Number i = new Integer(ilb_56);
          if ((1 > i.intValue()) || (i.intValue() > forca2.size())) 
            UTIL.RunTime("Illegal index");
          if (UTIL.equals(forca2.get(i.intValue() - 1), tab.get(origem))) 
            indice_origem = UTIL.NumberToInt(UTIL.clone(i));
        }
        for (int ilb_68 = 1; ilb_68 <= forca2.size(); ilb_68++) {
          Number i = new Integer(ilb_68);
          if ((1 > i.intValue()) || (i.intValue() > forca2.size())) 
            UTIL.RunTime("Illegal index");
          if (UTIL.equals(forca2.get(i.intValue() - 1), tab.get(destino))) 
            indice_destino = UTIL.NumberToInt(UTIL.clone(i));
        }
        Boolean cond_77 = null;
        if ((cond_77 = Boolean.valueOf(UTIL.equals(tab.get(origem), new quotes.RATO1()))).booleanValue()) 
          cond_77 = Boolean.valueOf(UTIL.equals(tab.get(destino), new quotes.ELEFANTE2()));
        if (cond_77.booleanValue()) 
          return Boolean.TRUE;
        Boolean cond_89 = null;
        if ((cond_89 = Boolean.valueOf(UTIL.equals(tab.get(origem), new quotes.RATO2()))).booleanValue()) 
          cond_89 = Boolean.valueOf(UTIL.equals(tab.get(destino), new quotes.ELEFANTE1()));
        if (cond_89.booleanValue()) 
          return Boolean.TRUE;
        Boolean cond_101 = null;
        if ((cond_101 = Boolean.valueOf(UTIL.equals(tab.get(origem), new quotes.ELEFANTE1()))).booleanValue()) 
          cond_101 = Boolean.valueOf(UTIL.equals(tab.get(destino), new quotes.RATO2()));
        if (cond_101.booleanValue()) 
          return Boolean.FALSE;
        Boolean cond_113 = null;
        if ((cond_113 = Boolean.valueOf(UTIL.equals(tab.get(origem), new quotes.ELEFANTE2()))).booleanValue()) 
          cond_113 = Boolean.valueOf(UTIL.equals(tab.get(destino), new quotes.RATO1()));
        if (cond_113.booleanValue()) 
          return Boolean.FALSE;
        if (indice_origem.intValue() >= indice_destino.intValue()) 
          return Boolean.TRUE;
        return Boolean.FALSE;
      }
    }
    finally {
      sentinel.leaving(((TabuleiroSentinel)sentinel).validaMaisForte);
    }
  }
// ***** VDMTOOLS END Name=validaMaisForte#2|List|List


// ***** VDMTOOLS START Name=pre_validaMaisForte#2|List|List KEEP=NO
  public Boolean pre_validaMaisForte (final List origem, final List destino) throws CGException {
    Boolean varRes_3 = null;
    if ((varRes_3 = validCoords(origem)).booleanValue()) 
      varRes_3 = validCoords(destino);
    return varRes_3;
  }
// ***** VDMTOOLS END Name=pre_validaMaisForte#2|List|List

}
;
