//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\joao\\Desktop\\MFES-RTFS\\TestJogador.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class TestJogador implements EvaluatePP {

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=TestJogadorSentinel KEEP=NO
  class TestJogadorSentinel extends Sentinel {

    public final int TestPecas = 0;

    public final int TestReset = 1;

    public final int AssertTrue = 2;

    public final int TestDerrota = 3;

    public final int nr_functions = 4;


    public TestJogadorSentinel () throws CGException {}


    public TestJogadorSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=TestJogadorSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new TestJogadorSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_TestJogador KEEP=NO
  private void vdm_init_TestJogador () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_TestJogador


// ***** VDMTOOLS START Name=TestJogador KEEP=NO
  public TestJogador () throws CGException {
    vdm_init_TestJogador();
  }
// ***** VDMTOOLS END Name=TestJogador


// ***** VDMTOOLS START Name=AssertTrue#1|Boolean KEEP=NO
  public void AssertTrue (final Boolean a) throws CGException {
    sentinel.entering(((TestJogadorSentinel)sentinel).AssertTrue);
    try {
      if (!this.pre_AssertTrue(a).booleanValue()) 
        UTIL.RunTime("Precondition failure in AssertTrue");
      return;
    }
    finally {
      sentinel.leaving(((TestJogadorSentinel)sentinel).AssertTrue);
    }
  }
// ***** VDMTOOLS END Name=AssertTrue#1|Boolean


// ***** VDMTOOLS START Name=pre_AssertTrue#1|Boolean KEEP=NO
  public Boolean pre_AssertTrue (final Boolean a) throws CGException {
    return a;
  }
// ***** VDMTOOLS END Name=pre_AssertTrue#1|Boolean


// ***** VDMTOOLS START Name=TestPecas KEEP=NO
  public void TestPecas () throws CGException {
    sentinel.entering(((TestJogadorSentinel)sentinel).TestPecas);
    try {
      Jogador p = new Jogador(new Integer(1));
      Jogador p2 = new Jogador(new Integer(2));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.LEAO2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.CAO2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.GATO2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.RATO2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.ELEFANTE2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.LEOPARDO2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.TIGRE2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p2.VerificaSeTemPeca(new quotes.LOBO2()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.LEAO1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.CAO1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.GATO1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.RATO1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.ELEFANTE1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.LEOPARDO1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.TIGRE1()), Boolean.TRUE)));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.VerificaSeTemPeca(new quotes.LOBO1()), Boolean.TRUE)));
    }
    finally {
      sentinel.leaving(((TestJogadorSentinel)sentinel).TestPecas);
    }
  }
// ***** VDMTOOLS END Name=TestPecas


// ***** VDMTOOLS START Name=TestDerrota KEEP=NO
  public void TestDerrota () throws CGException {
    sentinel.entering(((TestJogadorSentinel)sentinel).TestDerrota);
    try {
      Jogador p = new Jogador(new Integer(1));
      AssertTrue(Boolean.valueOf(UTIL.equals(p.perdeu(), Boolean.FALSE)));
      p.decTotalPieces();
      p.decTotalPieces();
      p.decTotalPieces();
      p.decTotalPieces();
      p.decTotalPieces();
      p.decTotalPieces();
      p.decTotalPieces();
      p.decTotalPieces();
      AssertTrue(Boolean.valueOf(UTIL.equals(p.perdeu(), Boolean.TRUE)));
    }
    finally {
      sentinel.leaving(((TestJogadorSentinel)sentinel).TestDerrota);
    }
  }
// ***** VDMTOOLS END Name=TestDerrota


// ***** VDMTOOLS START Name=TestReset KEEP=NO
  public void TestReset () throws CGException {
    sentinel.entering(((TestJogadorSentinel)sentinel).TestReset);
    try {
      Jogador p = new Jogador(new Integer(1));
      AssertTrue(Boolean.valueOf(p.getPecas().intValue() == 8));
      p.decTotalPieces();
      AssertTrue(Boolean.valueOf(p.getPecas().intValue() == 7));
      p.resetPecas();
      AssertTrue(Boolean.valueOf(p.getPecas().intValue() == 8));
    }
    finally {
      sentinel.leaving(((TestJogadorSentinel)sentinel).TestReset);
    }
  }
// ***** VDMTOOLS END Name=TestReset

}
;
