//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\joao\\Desktop\\MFES-RTFS\\TestTabuleiro.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.List;
import java.util.ArrayList;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class TestTabuleiro implements EvaluatePP {

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=TestTabuleiroSentinel KEEP=NO
  class TestTabuleiroSentinel extends Sentinel {

    public final int AssertTrue = 0;

    public final int TestJogada = 1;

    public final int nr_functions = 2;


    public TestTabuleiroSentinel () throws CGException {}


    public TestTabuleiroSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=TestTabuleiroSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new TestTabuleiroSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_TestTabuleiro KEEP=NO
  private void vdm_init_TestTabuleiro () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_TestTabuleiro


// ***** VDMTOOLS START Name=TestTabuleiro KEEP=NO
  public TestTabuleiro () throws CGException {
    vdm_init_TestTabuleiro();
  }
// ***** VDMTOOLS END Name=TestTabuleiro


// ***** VDMTOOLS START Name=AssertTrue#1|Boolean KEEP=NO
  public void AssertTrue (final Boolean a) throws CGException {
    sentinel.entering(((TestTabuleiroSentinel)sentinel).AssertTrue);
    try {
      if (!this.pre_AssertTrue(a).booleanValue()) 
        UTIL.RunTime("Precondition failure in AssertTrue");
      return;
    }
    finally {
      sentinel.leaving(((TestTabuleiroSentinel)sentinel).AssertTrue);
    }
  }
// ***** VDMTOOLS END Name=AssertTrue#1|Boolean


// ***** VDMTOOLS START Name=pre_AssertTrue#1|Boolean KEEP=NO
  public Boolean pre_AssertTrue (final Boolean a) throws CGException {
    return a;
  }
// ***** VDMTOOLS END Name=pre_AssertTrue#1|Boolean


// ***** VDMTOOLS START Name=TestJogada KEEP=NO
  public void TestJogada () throws CGException {
    sentinel.entering(((TestTabuleiroSentinel)sentinel).TestJogada);
    try {
      Tabuleiro tab = new Tabuleiro();
      tab.reset();
      List tmpSeq_4 = new ArrayList();
      tmpSeq_4.add(new Integer(1));
      tmpSeq_4.add(new Integer(1));
      List tmpSeq_8 = new ArrayList();
      tmpSeq_8.add(new Integer(1));
      tmpSeq_8.add(new Integer(2));
      tab.jogada(tmpSeq_4, tmpSeq_8);
      List tmpSeq_15 = new ArrayList();
      tmpSeq_15.add(new Integer(1));
      tmpSeq_15.add(new Integer(2));
      AssertTrue(Boolean.valueOf(UTIL.equals(tab.getPiece(tmpSeq_15), new quotes.LEAO1())));
      List tmpSeq_21 = new ArrayList();
      tmpSeq_21.add(new Integer(9));
      tmpSeq_21.add(new Integer(1));
      List tmpSeq_25 = new ArrayList();
      tmpSeq_25.add(new Integer(9));
      tmpSeq_25.add(new Integer(2));
      tab.jogada(tmpSeq_21, tmpSeq_25);
      List tmpSeq_30 = new ArrayList();
      tmpSeq_30.add(new Integer(3));
      tmpSeq_30.add(new Integer(7));
      List tmpSeq_34 = new ArrayList();
      tmpSeq_34.add(new Integer(4));
      tmpSeq_34.add(new Integer(7));
      tab.jogada(tmpSeq_30, tmpSeq_34);
      List tmpSeq_39 = new ArrayList();
      tmpSeq_39.add(new Integer(7));
      tmpSeq_39.add(new Integer(7));
      List tmpSeq_43 = new ArrayList();
      tmpSeq_43.add(new Integer(6));
      tmpSeq_43.add(new Integer(7));
      tab.jogada(tmpSeq_39, tmpSeq_43);
      List tmpSeq_48 = new ArrayList();
      tmpSeq_48.add(new Integer(4));
      tmpSeq_48.add(new Integer(7));
      List tmpSeq_52 = new ArrayList();
      tmpSeq_52.add(new Integer(5));
      tmpSeq_52.add(new Integer(7));
      tab.jogada(tmpSeq_48, tmpSeq_52);
      List tmpSeq_57 = new ArrayList();
      tmpSeq_57.add(new Integer(6));
      tmpSeq_57.add(new Integer(7));
      List tmpSeq_61 = new ArrayList();
      tmpSeq_61.add(new Integer(5));
      tmpSeq_61.add(new Integer(7));
      tab.jogada(tmpSeq_57, tmpSeq_61);
      List tmpSeq_66 = new ArrayList();
      tmpSeq_66.add(new Integer(3));
      tmpSeq_66.add(new Integer(1));
      List tmpSeq_70 = new ArrayList();
      tmpSeq_70.add(new Integer(4));
      tmpSeq_70.add(new Integer(1));
      tab.jogada(tmpSeq_66, tmpSeq_70);
      List tmpSeq_75 = new ArrayList();
      tmpSeq_75.add(new Integer(7));
      tmpSeq_75.add(new Integer(1));
      List tmpSeq_79 = new ArrayList();
      tmpSeq_79.add(new Integer(6));
      tmpSeq_79.add(new Integer(1));
      tab.jogada(tmpSeq_75, tmpSeq_79);
      List tmpSeq_84 = new ArrayList();
      tmpSeq_84.add(new Integer(4));
      tmpSeq_84.add(new Integer(1));
      List tmpSeq_88 = new ArrayList();
      tmpSeq_88.add(new Integer(5));
      tmpSeq_88.add(new Integer(1));
      tab.jogada(tmpSeq_84, tmpSeq_88);
      List tmpSeq_95 = new ArrayList();
      tmpSeq_95.add(new Integer(8));
      tmpSeq_95.add(new Integer(6));
      AssertTrue(Boolean.valueOf(UTIL.equals(tab.getPiece(tmpSeq_95), new quotes.CAO2())));
      List tmpSeq_103 = new ArrayList();
      tmpSeq_103.add(new Integer(8));
      tmpSeq_103.add(new Integer(7));
      AssertTrue(Boolean.valueOf(UTIL.equals(tab.getPiece(tmpSeq_103), new quotes.VAZIO())));
      List tmpSeq_109 = new ArrayList();
      tmpSeq_109.add(new Integer(8));
      tmpSeq_109.add(new Integer(6));
      List tmpSeq_113 = new ArrayList();
      tmpSeq_113.add(new Integer(8));
      tmpSeq_113.add(new Integer(7));
      tab.jogada(tmpSeq_109, tmpSeq_113);
      List tmpSeq_118 = new ArrayList();
      tmpSeq_118.add(new Integer(5));
      tmpSeq_118.add(new Integer(1));
      List tmpSeq_122 = new ArrayList();
      tmpSeq_122.add(new Integer(6));
      tmpSeq_122.add(new Integer(1));
      tab.jogada(tmpSeq_118, tmpSeq_122);
      tab.reset();
      List tmpSeq_130 = new ArrayList();
      tmpSeq_130.add(new Integer(1));
      tmpSeq_130.add(new Integer(1));
      AssertTrue(Boolean.valueOf(UTIL.equals(tab.getPiece(tmpSeq_130), new quotes.LEAO1())));
      List tmpSeq_136 = new ArrayList();
      tmpSeq_136.add(new Integer(3));
      tmpSeq_136.add(new Integer(1));
      List tmpSeq_140 = new ArrayList();
      tmpSeq_140.add(new Integer(4));
      tmpSeq_140.add(new Integer(1));
      tab.jogada(tmpSeq_136, tmpSeq_140);
      List tmpSeq_145 = new ArrayList();
      tmpSeq_145.add(new Integer(7));
      tmpSeq_145.add(new Integer(1));
      List tmpSeq_149 = new ArrayList();
      tmpSeq_149.add(new Integer(6));
      tmpSeq_149.add(new Integer(1));
      tab.jogada(tmpSeq_145, tmpSeq_149);
      List tmpSeq_154 = new ArrayList();
      tmpSeq_154.add(new Integer(4));
      tmpSeq_154.add(new Integer(1));
      List tmpSeq_158 = new ArrayList();
      tmpSeq_158.add(new Integer(5));
      tmpSeq_158.add(new Integer(1));
      tab.jogada(tmpSeq_154, tmpSeq_158);
      List tmpSeq_163 = new ArrayList();
      tmpSeq_163.add(new Integer(8));
      tmpSeq_163.add(new Integer(6));
      List tmpSeq_167 = new ArrayList();
      tmpSeq_167.add(new Integer(8));
      tmpSeq_167.add(new Integer(7));
      tab.jogada(tmpSeq_163, tmpSeq_167);
      List tmpSeq_172 = new ArrayList();
      tmpSeq_172.add(new Integer(5));
      tmpSeq_172.add(new Integer(1));
      List tmpSeq_176 = new ArrayList();
      tmpSeq_176.add(new Integer(6));
      tmpSeq_176.add(new Integer(1));
      tab.jogada(tmpSeq_172, tmpSeq_176);
      List tmpSeq_181 = new ArrayList();
      tmpSeq_181.add(new Integer(1));
      tmpSeq_181.add(new Integer(2));
      List tmpSeq_185 = new ArrayList();
      tmpSeq_185.add(new Integer(1));
      tmpSeq_185.add(new Integer(5));
      tab.jogada(tmpSeq_181, tmpSeq_185);
    }
    finally {
      sentinel.leaving(((TestTabuleiroSentinel)sentinel).TestJogada);
    }
  }
// ***** VDMTOOLS END Name=TestJogada

}
;
